[package]
name = "btclip"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
image = "0.25.10"
tokio = { version = "1.53.1", features = ["full"] }
widestring = "0.4"
winapi = { version = "0.3", features = ["winuser", "shellapi", "winbase"] }

[dependencies.windows]
version = "0.62.2"
features = [
    "Foundation",
    "Storage_Streams",
    "Networking",                  # Required parent for Sockets
    "Networking_Sockets",
    "Devices",                     # Required parent for Bluetooth
    "Devices_Bluetooth",           # Required parent for Rfcomm
    "Devices_Bluetooth_Rfcomm",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
]

