#[derive(Debug, PartialEq)]
pub enum FrameType {
    Text = 0x01,
    Image = 0x02,
}

#[derive(Debug, PartialEq)]
pub struct ClipboardFrame {
    pub frame_type: FrameType,
    pub length: u32,
    pub payload: Vec<u8>,
}

#[derive(Debug, PartialEq)]
pub enum ProtocolError {
    IncompleteHeader,
    UnknownFrameType,
    IncompletePayload,
}

pub fn encode_frame(frame_type: FrameType, payload: &[u8]) -> Vec<u8> {
    let length = payload.len() as u32;

    let mut buffer = Vec::with_capacity(5 + payload.len());
    buffer.push(frame_type as u8);
    buffer.extend_from_slice(&length.to_be_bytes());
    buffer.extend_from_slice(payload);

    buffer
}

pub fn decode_frame(data: &[u8]) -> Result<ClipboardFrame, ProtocolError> {
    if data.len() < 5 {
        return Err(ProtocolError::IncompleteHeader);
    }

    let type_byte = data[0];
    let frame_type = match type_byte {
        0x01 => FrameType::Text,
        0x02 => FrameType::Image,
        _ => return Err(ProtocolError::UnknownFrameType),
    };

    let mut len_bytes = [0u8; 4];
    len_bytes.copy_from_slice(&data[1..5]);

    let length = u32::from_be_bytes(len_bytes);

    if data.len() < 5 + length as usize {
        return Err(ProtocolError::IncompletePayload);
    }

    let payload = data[5..5 + length as usize].to_vec();

    Ok(ClipboardFrame {
        frame_type,
        length,
        payload,
    })
}

// tests were generated by AI! ;)

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_encode_text_frame() {
        let payload = b"Hello"; // Creates a byte slice &[u8]
        let encoded = encode_frame(FrameType::Text, payload);

        // Expected: [0x01, 0x00, 0x00, 0x00, 0x05, 'H', 'e', 'l', 'l', 'o']
        assert_eq!(encoded.len(), 10);
        assert_eq!(encoded[0], 0x01);
        assert_eq!(encoded[4], 5); // The length byte
    }

    #[test]
    fn test_decode_valid_frame() {
        // Manually constructing a valid packet
        let raw_data = vec![0x01, 0x00, 0x00, 0x00, 0x05, b'H', b'e', b'l', b'l', b'o'];

        let result = decode_frame(&raw_data);
        assert!(result.is_ok());

        let frame = result.unwrap();
        assert_eq!(frame.frame_type, FrameType::Text);
        assert_eq!(frame.length, 5);
        assert_eq!(frame.payload, b"Hello".to_vec());
    }

    #[test]
    fn test_decode_incomplete_header() {
        let raw_data = vec![0x01, 0x00]; // Only 2 bytes, needs 5
        let result = decode_frame(&raw_data);
        assert_eq!(result, Err(ProtocolError::IncompleteHeader));
    }
}
